config/routes.rb
Frugalistas::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  resources :convos do
    resources :messages
  end
  resources :messages

  resources :transactions
  resources :trusts do 
    resource :transactions  
  end

  root :to => "users#show"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :convo_id, :author_id, :recipient_id, :body

  validates :convo_id, :author_id, :recipient_id, :body, presence: true

  belongs_to(
    :convo,
    class_name: "Convo",
    foreign_key: :convo_id,
    primary_key: :id
  )
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  belongs_to(
    :recipient,
    class_name: "User",
    foreign_key: :recipient_id,
    primary_key: :id
  )

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @convos = Convo.all
    @messages = Message.where(author_id: current_user.id)
    Message.where(recipient_id: current_user.id).each {|msg| @messages << msg}
    @messages.sort! { |a,b| a.created_at <=> b.created_at }
    render :index
  end

  def show
    @message = Message.find(:id)
  end

  def new
    render :new
  end

  def create
    params[:message][:recipient_id] = User.find_by_username(params[:message][:recipient]).id
    params[:message][:author_id] = current_user.id
    p = [params[:message][:recipient_id],params[:message][:author_id]]
    p.sort!
    pairing = p[0].to_s + "a" + p[1].to_s
    convo = Convo.find_by_pairing(pairing)
    if p[0] == p[1]
      flash[:errors] = ["You can't message yourself!"]
      redirect_to :new
    else 
      if convo.nil?
        convo = Convo.new(pairing: pairing)
        convo.save
      end
      params[:message][:convo_id] = convo.id
      
      @message = Message.new(
        convo_id: params[:message][:convo_id],
        author_id: current_user.id,
        recipient_id: params[:message][:recipient_id],
        body: params[:message][:body]
      )
      if @message.save
        @messages = Message.where(author_id: current_user.id)
        Message.where(recipient_id: current_user.id).each {|msg| @messages << msg}
        redirect_to messages_url
      else
        @messages = Message.where(author_id: current_user.id)
        Message.where(recipient_id: current_user.id).each {|msg| @messages << msg}
        render :index
      end
    end
  end
  
  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    
    @messages = Message.where(author_id: current_user.id)
    Message.where(recipient_id: current_user.id).each {|msg| @messages << msg}

    render :index
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<%= render "shared/sidebar" %>

<section class="content-body">

<% @messages.each do |message| %>

	<h3>From: <%= message.author.username %>, To: <%= message.recipient.username %>, Date: <%= message.created_at %> </h3>
	
	<p><%= message.body %> <%= button_to "Delete", message_url(message.id), 
		{method: :delete, class: "button button-delete"} %></p>
	
<% end %>

<%= link_to "Send New Message", new_message_url, class: "button button-send-message"%>

</section>

app/views/messages/new.html.erb
<form action="<%= messages_url %>" method="post">

	<input type="hidden" 
	name="authenticity_token" 
	value="<%= form_authenticity_token %>">
	
	<label for="recipient">To:</label><input type="text" name="message[recipient]" value="" id="recipient">
	
	<br>
	
	<label for="body">Message:</label>
	<input type="text" name="message[body]" value="" id="body">
	
	<p><input type="submit" value="Send"></p>
</form>