config/routes.rb
Frugalistas::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  resources :convos do
    resources :messages
  end
  resources :messages

  resources :transactions
  resources :trusts do 
    resource :transactions  
  end

  root :to => "users#show"
end

app/models/trust.rb
class Trust < ActiveRecord::Base
  attr_accessible :entrustor_id, :trustee_id
  
  validates :entrustor_id, :trustee_id, presence: true
  
  belongs_to(
    :entrustors,
    class_name: "User",
    foreign_key: :trustee_id,
    primary_key: :id
  )
  
  belongs_to(
    :trustees,
    class_name: "User",
    foreign_key: :entrustor_id,
    primary_key: :id
  )
  
  has_many :username, through: :users, source: :username 
  
end

app/controllers/trusts_controller.rb
class TrustsController < ApplicationController
  
  def index
    @trustees = current_user.trustees
    @entrustors = current_user.entrustors
    render :index
  end
  
  def create
    user = User.find_by_username(params[:trust][:trustee])
    @trustees = current_user.trustees
    @entrustors = current_user.entrustors
    
    if user.nil?
      flash[:alert] = ["No such user!"]
      render partial: "transactions/trustee_list"
    elsif user == current_user
      flash[:alert] = ["You can't entrust yourself"]
      render partial: "transactions/trustee_list"
    elsif !current_user.trustees.where(trustee_id: user.id).empty?
      flash[:alert] = ["You've already entrusted this user."]
      render partial: "transactions/trustee_list"
    else

      @trustee = current_user.trustees.new(trustee_id: user.id)
    
      unless @trustee.save
        flash[:errors] = @trustee.errors.full_messages
      end
      
      @trustees = current_user.trustees
      @entrustors = current_user.entrustors

      if request.xhr?
        render partial: "transactions/trustee_list"
      else
        redirect_to trusts_url
      end
    end
    
  end
  
  def show
    # fail
    redirect_to trust_url()
  end
  

  def destroy
    @trust = Trust.find_by_id(params[:id])
    @trust.destroy
    
    @trustees = current_user.trustees
    @entrustors = current_user.entrustors

    if request.xhr?
      render partial: "transactions/trustee_list"
    else
      redirect_to trusts_url
    end
  end
  
  def trustee_detail
    
  end
  
end

app/helpers/trusts_helper.rb
module TrustsHelper
end

app/views/trusts/index.html.erb
<%= render "shared/sidebar" %>

<section class="content-body">

<h3>Trustees</h3>

<h4>People whom you've entrusted (trustees):</h4>

<div class="trustee-list">
	<%= render partial: "transactions/trustee_list", local: @trustees %>
</div>

<br>

<form 
	id="trustee-new-form"
	action="<%= trusts_url %>" 
	method="post" 
	data-remote="true">
	
	
	<input type="hidden" 
	name="authenticity_token" 
	value="<%= form_authenticity_token %>">
	
	<label for="new_trustee">New Trustee:</label>
		<div class="input">
			<input type="text" name="trust[trustee]" value="" id="new_trustee">
		</div>
	<input type="submit" class="button button-add" value="Add">
</form>

<br>

<h4>People who have entrusted you (entrustors):</h4>
	<div class="entrustors">
		<% if @entrustors.empty? %>
				<p id="no-entrustors">Nobody trusts you :-(</p>
		<% else %>
			<% @entrustors.each do |entrustor|  %>
				<% user = User.find(entrustor.entrustor_id) %>
				<tr id="<%= user.id %>">
					<td>
						
						<a href="<%= trust_transactions_url(user.id) %>" data-remote="true">
							<%= user.username %>
						</a>
						
					</td>
				</tr>
			<% end %>
		<% end %>
	</div>
	
	
	<div class="entrustor-transactions">
		(Select an entrustor to see their transactions)
	</div>
	
</section>


<script>
$(document).ready(function(event){
	$(".entrustors").on("ajax:success", "a", function(event, data){

	  $(".entrustor-transactions").html(data);
	});

	
  $("#trustee-new-form").on("ajax:success", function(event, data){
    console.log(data);
    var $form = $(this);

    $(".trustee-list").html(data);
    $form[0].reset();
  });
	
	
  // $("form.button-remove").on("ajax:success", function(event, data){
  //   var $form = $(this);
  // 		var $li = $form.closest(".trustee");
  // 		
  // 		console.log("hi")
  // 
  //   $(".trustee-list").html(data);
  //   $form[0].reset();
  // });
});

</script>



<!-- // <script>
// $(document).ready(function(event){
//   $("section").on("click", "a", function(event){
//     event.preventDefault();
//     var $a = $(this);
//     var url = $a.attr("href");
//     console.log(url);
//     $.ajax({
//       url: url,
//       method: "GET",
//       dataType: "html",
//       success: function(data){
//         console.log(data);
//         $("#cat-featured").html(data);
//       }
//     });
//   });
// });
 </script> -->

app/views/trusts/show.html.erb
<%= render "shared/sidebar" %>

<section class="content-body">
	
	<h3><%= @trustee.username %>'s transactions</h3>
	
<table>
<tr>
  <th></th>
  <th>Date</th>
  <th>Description</th>
  <th>Amount</th>
  <th>Category</th>
  <th>Privacy</th>
  <th></th>
</tr>
<% @transactions.each do |tran| %>
  <tr data-id="<%= tran.id %>">
    <form action="<%= transaction_url(tran) %>" method="post">
      <input type="hidden" name="_method" value="put">

      <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

      <td class="blank"></td>
      <td class="date">
        <%= tran.date %>
      </td>
      <td class="description">
        <%= tran.description %>
      </td>
      <td class="amount">
        <%= tran.amount %>
      </td>
      <td class="category">
        <input type="text" name="transaction[category]"
        value="<%= tran.category %>" id="category">
      </td>

      <td class="privacy">
        <select name="transaction[privacy]">
          <option value="private">
          private</option>
          <option value="shared"
          "<%= tran.privacy == 'shared' ? " selected='selected'" : ''%>">
          shared</option>
        </select>
        </td>

      <td class="edit">
        <input type="submit" value="Update">
      </td>

    </form>

    <td class="remove_button">
      <%= button_to "Remove", transaction_url(tran),
      method: :delete %>
    </td>

  </tr>
<% end %>




<form action="<% transactions_url %>" method="POST">

  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <td class="blank"></td>
  <td class="date"><input type="date" name="transaction[date]"
  value="" id="date"></td>
  <td class="description"><input type="text" name="transaction[description]"
  value="description" id="description"></td>
  <td class="amount"><input type="text" name="transaction[amount]"
  value="amount" id="amount"></td>
  <td class="category"><input type="text" name="transaction[category]"
  value="" id="category"></td>
  <td class="privacy">
    <select name="transaction[privacy]">
      <option value="private" selected="selected">private</option>
      <option value="shared">shared</option>
    </select>
  </td>
  <td class="add"><input type="submit" value="Add"></td>
  <td class="blank"></td>
</form>

</table>

</section>