config/routes.rb
Frugalistas::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  resources :convos do
    resources :messages
  end
  resources :messages

  resources :transactions
  resources :trusts do 
    resource :transactions  
  end

  root :to => "users#show"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = current_user.transactions.all
    @transactions.sort! { |a,b| b.date <=> a.date }
    @transactions.sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def show
    @trustees = current_user.trustees
    @entrustors = current_user.entrustors

    @entrustor = User.find(params[:trust_id])
    @entrustor_trans = Transaction.where(user_id: params[:trust_id], privacy: "shared")

    if request.xhr?
      render partial: "transactions/trans", locals: {user: @entrustor}
    else
      render :show
    end
  end

  def edit
    @transactions = current_user.transactions.all
    @transactions.sort! { |a,b| b.date <=> a.date }
    @transactions.sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def update
    @transaction = Transaction.find_by_id(params[:id])
    if @transaction.update_attributes(params[:transaction])
      flash[:errors] = @transaction.errors.full_messages
    else
      flash[:errors] = @transaction.errors.full_messages
    end

    @transactions = current_user.transactions.all
    @transactions.sort! { |a,b| b.date <=> a.date }
    @transactions.sort! { |a,b| b.created_at <=> a.created_at }
    redirect_to transactions_url
  end

  def create
    params[:transaction][:user_id] = current_user.id
    @transaction = Transaction.new(params[:transaction])
    unless @transaction.save
      flash[:errors] = @transaction.errors.full_messages
    end
    
    @transactions = current_user.transactions.all
    @transactions.sort! { |a,b| b.date <=> a.date }
    @transactions.sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def destroy
    @transaction = Transaction.find_by_id(params[:id])
    @transaction.destroy
    @transactions = current_user.transactions.all
    @transactions.sort! { |a,b| b.date <=> a.date }
    @transactions.sort! { |a,b| b.created_at <=> a.created_at }
    redirect_to transactions_url
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_trans.html.erb
<section><h3><%= user.username %>'s transactions:</h3>

<table>
<tr>
  <th>Date</th>
  <th>Description</th>
  <th>Amount</th>
  <th>Category</th>
</tr>
<% user.transactions.each do |tran| %>
  <tr data-id="<%= tran.id %>">
	  <td class="date">
	    <%= tran.date %>
	  </td>
	  <td class="description">
	    <%= tran.description %>
	  </td>
	  <td class="amount">
			<%= number_to_currency(tran.amount) %>
	  </td>
	  <td class="category">
	    <%= tran.category %>
	  </td>
  </tr>
<% end %>
</table>
</section>

app/views/transactions/_trustee_list.html.erb
<div class="error-bars group">
  <% if flash[:alert] && !flash[:alert].empty? %>
    <% flash[:alert].each do |error| %>
			<div class="error-msg">
	      <%= error %>
			</div>
    <% end %>
  <% end %>
	<% flash[:alert] = nil %>
</div>

<% if @trustees.empty? %>
	<p id="no-trustees">Ya gotta trust somebody...</p>
<% else %>
	<table>
	<% @trustees.each do |trustee| %>
		<% user = User.find(trustee.trustee_id) %>
		<tr id="<%= user.id %>">
			<td>
				<%= user.username %>
			</td>
			<td class="remove_button">
				<%= button_to "Remove", trust_url(trustee), 
				{ method: :delete,
					class: "button button-remove", 
						"data-remote" => "true"} %>
			</td>
		</tr>
	<% end %>
</table>
<% end %>

app/views/transactions/index.html.erb
<%= render "shared/sidebar" %>


<section class="content-body">
	
<h3><%= current_user.username %>'s transactions</h3>

<table>
<tr>

  <th>Date</th>
  <th>Description</th>
  <th>Amount</th>
  <th>Category</th>
  <th>Privacy</th>

</tr>
<% @transactions.each do |tran| %>
  <tr data-id="<%= tran.id %>">
    <form action="<%= transaction_url(tran) %>" method="post">
      <input type="hidden" name="_method" value="put">

      <input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">


      <td class="date">
        <%= tran.date %>
      </td>
      <td class="description">
        <%= tran.description %>
      </td>
      <td class="amount">
        <%= number_to_currency(tran.amount) %>
      </td>
      <td class="category">
				<div class="input">
	        <input type="text" name="transaction[category]"
	        value="<%= tran.category %>" id="category">
				</div>
      </td>

      <td class="privacy">
        <select name="transaction[privacy]">
          <option value="private">
          private</option>
          <option value="shared"
          "<%= tran.privacy == 'shared' ? " selected='selected'" : ''%>">
          shared</option>
        </select>
        </td>

      <td class="edit">
        <input type="submit" class="button button-update" value="Update">
      </td>

    </form>

    <td class="remove_button">
      <%= button_to "Remove", transaction_url(tran),
      {method: :delete, class: ["button", "button-remove"]} %>
    </td>

  </tr>
<% end %>




<form action="<% transactions_url %>" method="POST">

  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <td class="date">
		<div class="input">
			<input type="date" 
			name="transaction[date]"
		  value="" id="date">
		</div>
	</td>
  <td class="description"><div class="input"><input type="text" name="transaction[description]"
  value="description" id="description"></div></td>
  <td class="amount"><div class="input"><input type="text" name="transaction[amount]"
  value="amount" id="amount"></div></td>
  <td class="category"><div class="input"><input type="text" name="transaction[category]"
  value="" id="category"></div></td>
  <td class="privacy">
    <select name="transaction[privacy]">
      <option value="private" selected="selected">private</option>
      <option value="shared">shared</option>
    </select>
  </td>
  <td class="add"><input class="button" type="submit" value="Add"></td>
  <td class="blank"></td>
</form>

</table>

</section>

app/views/transactions/show.html.erb
<%= render "shared/sidebar" %>

<section class="content-body">

<h3>Trustees</h3>

<h4>People whom you've entrusted (trustees):</h4>
<% if @trustees.empty? %>
	<p id="no-trustees">Ya gotta trust somebody...</p>
<% else %>
	<table>
	<% @trustees.each do |trustee| %>
		<% user = User.find(trustee.trustee_id) %>
		<tr id="<%= user.id %>">
			<td>
				<%= user.username %>
			</td>
			<td class="remove_button">
				<%= button_to "Remove", trust_url(trustee), method: :delete %>
			</td>
		</tr>
	<% end %>
</table>
<% end %>

<br>

<form action="<%= trusts_url %>" method="post">
	<input type="hidden" 
	name="authenticity_token" 
	value="<%= form_authenticity_token %>">
	
	<label for="new_trustee">New Trustee:</label>
	<input type="text" name="trust[trustee]" value="" id="new_trustee">
	<input type="submit" value="Add">
</form>

<br>

<h4>People who have entrusted you (entrustors):</h4>
	<div class="entrustors">
		<% if @entrustors.empty? %>
				<p id="no-entrustors">Nobody trusts you :-(</p>
		<% else %>
			<% @entrustors.each do |entrustor|  %>
				<% user = User.find(entrustor.entrustor_id) %>
				<tr id="<%= user.id %>">
					<td>
						<%= link_to user.username, trust_transactions_url(user.id) %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</div>
	
<h3><%= @entrustor.username %>'s transactions:</h3>

<table>
<tr>
  <th>Date</th>
  <th>Description</th>
  <th>Amount</th>
  <th>Category</th>
</tr>
<% @entrustor_trans.each do |tran| %>
  <tr data-id="<%= tran.id %>">
	  <td class="date">
	    <%= tran.date %>
	  </td>
	  <td class="description">
	    <%= tran.description %>
	  </td>
	  <td class="amount">
	    <%= number_to_currency(tran.amount) %>
	  </td>
	  <td class="category">
	    <%= tran.category %>
	  </td>
  </tr>
<% end %>
</table>

</section>