config/routes.rb
Frugalistas::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  resources :convos do
    resources :messages
  end
  resources :messages

  resources :transactions
  resources :trusts do 
    resource :transactions  
  end

  root :to => "users#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frugalist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>


	<div class="error-bar group">
	  <% if flash[:errors] && !flash[:errors].empty? %>
	    <% flash[:errors].each do |error| %>
				<div class="error-msg">
		      <%= error %>
				</div>
	    <% end %>
	  <% end %>
		<% flash[:errors] = nil %>
	</div>

<header class="header">
	
  <% logo_ref = current_user.nil? ? new_session_url : user_url(current_user) %>
	
	<div class="header-wrapper group">
    <div class="header">
		<a href="<%= logo_ref %>">
    
      <div class="logo-test">
        <div class="logo-test2"></div>
      </div>
    </a>
    
      <span class="main-title">
        Frugalist
      </span>
    </div>
    
    
    

	<% if current_user.nil? %>

	<h1 class="logo">
		<a href="<%= new_session_url %>"></a>
	</h1>

	<% else %>

	  <ul class="head-right group">
	    <li><%= button_to "Logout", session_url, {method: :delete, class: ["button", "button-logout"]} %></li>
			
			<li id="profile">Profile: <%= link_to current_user.username,  user_url(current_user), class: ["button", "button-profile"] %></li>
	  </ul>
	<% end %>
	
  
  
</div>
	
</header>

<section class="main group">
<%= yield %>



</section>

<% if !current_user.nil? %>
	<footer class="footer group">
		<small class="footer-copy">
		</small>
		<nav class="footer-links">
			<ul class="group">
				<li><a href="#">About</a></li>
				<li><a href="#">Privacy</a></li>
			</ul>
		</nav>
	</footer>
<% end %>



</div>
</body>
</html>